services:
  api:
    image: ghcr.io/wewatch/api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - packages/api/.env
    working_dir: /usr/wewatch/packages/api
    ports:
      - 8080:8080
    restart: unless-stopped
